---
title: "Trivariate Viz"
---
```{r}
library(ggplot2)
library(mosaic)
library(fivethirtyeight)
```
```{r}
data(bechdel)
new_bechdel <- bechdel |>
  mutate(clean_test = factor(clean_test, c("nowomen", "notalk", "men", "dubious", "ok"))) |>
  mutate(half_decades = cut(year, breaks = seq(1969, 2014, by = 5)))
```

Use this file to generate a professional looking **trivariate** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.
```{r fig.width = 8, fig.height = 5.5}
  #| fig_cap: "Bechdel Test results from Movies from 1969-2014 per Half Decades" 
  #| fig_alt: "the plot shows the results from the Bechdel test of movies from 1969-2014. Movies passing the test peaked in the 90s. 
ggplot(new_bechdel, aes(fill = clean_test, x = half_decades)) +
  geom_bar(position = "fill") +
  labs(y = "Scores", x = "Half Decades", legend = "Results", title = "Results of Bechdel Test in movies from 1969-2014") +
  scale_fill_viridis_d() 
```


