---
title: "bw-solo-proj.qmd"
editor: visual
---

```{r}
#| echo: true
#| warning: false
#| error: false
#| code-fold: true
library(rnaturalearth)
library(sf)
library(maps)
library(mosaic)
library(gplots)
library(tidyverse)
library(readxl)
```

```{r}
#| echo: true
#| warning: false
#| error: false
#| code-fold: true
world_boundaries <- ne_countries(returnclass = "sf")
  
mbs_bird_records_by_county <- read_excel("solo project/mbs-bird-records-by-county.xlsx")
```

```{r}
#| echo: true
#| warning: false
#| error: false
#| code-fold: true

mn_loons <- mbs_bird_records_by_county |>
  filter(`County Names` == "Common Loon") |>
 pivot_longer(cols = c(2:88),
               names_to = "Counties",
               values_to = "Sightings") |>
  mutate(col1 = tolower(Counties)) |>
  mutate_if(is.numeric, ~replace(., is.na(.), 0))

midwest_boundaries <- st_as_sf(
  maps::map("county",
            region = c("minnesota"), 
            fill = TRUE, plot = FALSE))

midwest_boundaries2 <- midwest_boundaries|>
  mutate(ID = str_replace(ID, "minnesota,", ""))

midwest_boundaries2 |>
  left_join(mn_loons |> select(col1, Sightings), join_by(ID == col1 ))

#| fig-cap: "A Map of Common Loon Sitings in Minnesota counties"
#| fig-alt: "The more North and Rural the county is the more Loon sitings there are." 
midwest_boundaries2 |>
  left_join(mn_loons |> select(col1, Sightings), join_by(ID == col1 )) |>
 ggplot() +
   geom_sf(aes(fill = Sightings), color = "red") +
   theme_map() +
  scale_fill_viridis_c(option = "magma", direction = -1) +
  labs(title = "Map of Common Loon Sightings in Minnesota counties")

```
```{r}

#This plot shows that the northern counties of 
#Minnesota have the most loon sightings. This is 
#most likely because they are less urban areas and 
#therefore wild life is able to thrive. I choose 
#the loon becasue it is Minnesota's state bird, 
#and culturally important to the area. 
```

