---
title: "Univariate Viz"
---
```{r}
library(ggplot2)
```

Use this file for practice with the **univariate viz** in-class activity.  Refer to the class website for details.
# Import data
hikes <- read.csv("https://mac-stat.github.io/data/high_peaks.csv")
head(hikes)
```{r}
# Import data
hikes <- read.csv("https://mac-stat.github.io/data/high_peaks.csv")
head(hikes)

```
```{r}
# Use the ggplot function
ggplot(hikes, aes(x = rating))
```
```{r}
# Load the package
library(tidyverse)
```
```{r}
# Use the ggplot function
ggplot(hikes, aes(x = rating))

```
```{r}
ggplot(hikes, aes(x = rating))
```
```{r}
# added the bars to the bar chart
ggplot(hikes, aes(x = rating)) +
  geom_bar()

```
```{r}
# COMMENT on the change in the code and the corresponding change in the plot
ggplot(hikes, aes(x = rating)) +
  geom_bar() +
  labs(x = "Rating", y = "Number of hikes")
```
```{r}
# made the bars blue
ggplot(hikes, aes(x = rating)) +
  geom_bar(fill = "blue") +
  labs(x = "Rating", y = "Number of hikes")
```
```{r}
# gave the bars a orange boarder
ggplot(hikes, aes(x = rating)) +
  geom_bar(color = "orange", fill = "blue") +
  labs(x = "Rating", y = "Number of hikes")
```
```{r}
# made the background white
ggplot(hikes, aes(x = rating)) +
  geom_bar(color = "orange", fill = "blue")  +
  labs(x = "Rating", y = "Number of hikes") +
  theme_minimal()

```
```{r}
ggplot(hikes, aes(x = elevation)) +
  geom_bar() 
  
```
```{r}
ggplot(hikes, aes(x = elevation))
```
```{r}
# added thicker bars and clumped some together
ggplot(hikes, aes(x = elevation)) +
  geom_histogram()
```
```{r}
# added boarders 
ggplot(hikes, aes(x = elevation)) +
  geom_histogram(color = "white") 
```

```{r}
# filled in the bars with blue
ggplot(hikes, aes(x = elevation)) +
  geom_histogram(color = "white", fill = "blue") 
```
```{r}
# made the Xaxis and the Y axis feet and number of hikes
ggplot(hikes, aes(x = elevation)) +
  geom_histogram(color = "white") +
  labs(x = "Elevation (feet)", y = "Number of hikes")
```
```{r}
# combined mulitple data points makingthe bars very thick
ggplot(hikes, aes(x = elevation)) +
  geom_histogram(color = "white", binwidth = 1000) +
  labs(x = "Elevation (feet)", y = "Number of hikes")
```
```{r}
# made the bars very skinny
ggplot(hikes, aes(x = elevation)) +
  geom_histogram(color = "white", binwidth = 5) +
  labs(x = "Elevation (feet)", y = "Number of hikes")
```
```{r}
# COMMENT on the change in the code and the corresponding change in the plot
ggplot(hikes, aes(x = elevation)) +
  geom_histogram(color = "white", binwidth = 200) +
  labs(x = "Elevation (feet)", y = "Number of hikes")
```
```{r}
ggplot(hikes, aes(x = elevation)) +
  geom_density()
```

```{r}
ggplot(hikes, aes(x = elevation)) +
geom_density(color = "blue") +
geom_density(fill = "orange")
```
```{r}
# Data on students in this class
survey <- read.csv("https://hash-mac.github.io/stat112site-s25/data/survey.csv")

# World Cup data
world_cup <- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-11-29/worldcups.csv")


```

