---
title: "Mulivariate Viz"
---

Use this file for practice with the **mulivariate viz** in-class activity.  Refer to the class website for details.
```{r}
library(ggplot2)
# Import and check out data
education <- read.csv("https://mac-stat.github.io/data/sat.csv")
head(education)


```
```{r}

library(tidyverse)

# Import data
weather <- read.csv("https://mac-stat.github.io/data/weather_3_locations.csv") |> 
  mutate(date = as.Date(date))  

# Check out the first 6 rows
# What are the units of observation?
head(weather)
```
```{r}

ggplot(education, aes(x = sat)) + 
  geom_density()
ggplot(weather, aes(x = temp3pm, fill = location)) + 
  geom_density(alpha = 0.5)
ggplot(weather, aes(y = temp3pm, x = location)) + 
  geom_boxplot()
ggplot(weather, aes(x = temp3pm, fill = location)) + 
  geom_density(alpha = 0.5) + 
  facet_wrap(~ location)
# Don't worry about the syntax (we'll learn it soon)
woll <- weather |>
  filter(location == "Wollongong") |> 
  mutate(date = as.Date(date))  
ggplot(woll, aes(x = raintoday, fill = raintomorrow)) + 
  geom_bar()
 ggplot(woll, aes(x = raintoday, fill = raintomorrow)) + 
  geom_bar(position = "dodge")
 ggplot(woll, aes(x = raintoday, fill = raintomorrow)) + 
  geom_bar(position = "fill")
 ggplot(woll, aes(y = temp3pm, x = date)) +
   geom_line()
```
```{r}
ggplot(weather, aes(y = temp3pm, x = temp9am)) + 
  geom_point()
```
```{r}
ggplot(weather, aes(y = temp3pm, x = temp9am)) + 
  geom_point()
```
```{r}
ggplot(weather, aes(y = temp3pm, x = date)) + 
  geom_line()
```
```{r}
ggplot(weather, aes(x = raintoday, fill = raintomorrow)) + 
  geom_bar(position = "fill")
```
```{r}
education <- read.csv("https://mac-stat.github.io/data/sat.csv")
head(education)
```
```{r}
# A histogram would work too!
ggplot(education, aes(x = sat)) + 
  geom_density()
```
```{r}
# Construct a plot of sat vs expend
# Include a "best fit linear regression model"
ggplot(education, aes(y = sat, x = expend)) + 
  geom_point() + 
  geom_smooth(method = "lm")
```
```{r}
# Construct a plot of sat vs salary
# Include a "best fit linear regression model"
ggplot(education, aes(y = sat, x = salary)) + 
  geom_point() + 
  geom_smooth(method = "lm")
```
```{r}
ggplot(education, aes(y = sat, x = salary, color = expend)) + 
  geom_point() + 
  geom_smooth(method = "lm")
```
```{r}
ggplot(education, aes(y = sat, x = salary, color = cut(expend, 2))) + 
  geom_point() + 
  geom_smooth(se = FALSE, method = "lm")
```
```{r}
ggplot(education, aes(y = sat, x = salary, color = cut(expend, 3))) + 
  geom_point() + 
  geom_smooth(se = FALSE, method = "lm")
```
```{r}
ggplot(education, aes(x = fracCat)) + 
  geom_bar()
```
```{r}
ggplot(education, aes(x = sat, fill = fracCat)) + 
  geom_density(alpha = 0.5)
```
```{r}
ggplot(education, aes(y = sat, x = expend, color = fracCat)) + 
  geom_point() + 
  geom_smooth(method = "lm")
```
```{r}
# Remove the "State" column and use it to label the rows
# Then scale the variables
plot_data <- education |> 
  column_to_rownames("State") |> 
  data.matrix() |> 
  scale()

# Load the gplots package needed for heatmaps
library(gplots)
```
